# Required connection configs for Kafka producer, consumer, and admin
# Best practice for higher availability in librdkafka clients prior to 1.7
#session.timeout.ms=45000

#bootstrap.servers=<loaded from secrets vault>
#sasl.username=<loaded from secrets vault>
#sasl.password= <loaded from secrets vault>
#client.id=<loaded from secrets vault>

socket.keepalive.enable=True
socket.timeout.ms=30000
message.timeout.ms=30000
reconnect.backoff.ms=1000
reconnect.backoff.max.ms=10000
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN